### ISSUE TITLE
Frontend-Create an app wireframe

### ISSUE THREAD

**Issue by FernandoTorresL** [swat-flights/Master_Flights#10]
**Wireframe created in Adobe XD** https://xd.adobe.com/view/d2387c0a-9b3e-4c32-92c8-9bf9c3372d73-876b/

**Documentation:** https://www.notion.so/Wireframes-503a18f544b54348a89887b6d915bba7

**Comment by Lcaraballoc** [comment]
Wireframes version desktop cargados al Notion

**Comment by Lcaraballoc** [comment]
**Wireframe created in Adobe XD** https://xd.adobe.com/view/d2387c0a-9b3e-4c32-92c8-9bf9c3372d73-876b/
**Documentation:** https://www.notion.so/Wireframes-503a18f544b54348a89887b6d915bba7
